### PR TITLE
Large data fix (#51)

### LINKED ISSUE #51: Error with large datasets
The line

`totalSize <- nrow(coercedData[[1]])*ncol(coercedData[[1]]) +  nrow(coercedData[[2]])*ncol(coercedData[[2]])`

aims to calculate the total number of elements for comparison. However, if this results in a value outside the range of a 32-bit integer, the code errors with 

```
Running rCompare...
Coercing input data to data.frame
Error in if (totalSize > 2e+07) { : missing value where TRUE/FALSE needed
In addition: Warning message:
In nrow(coercedData[[1]]) * ncol(coercedData[[1]]) + nrow(coercedData[[2]]) *  :
  NAs produced by integer overflow
```

This code is just there to warn the user about a possible long run time, so it'd be preferable to remove this rather than cause this error, although I imagine there are probably numerous ways to fix it.

### PR DESCRIPTION
**Pull request by rnobleeddy**
## Description
Fixes #51. Cause is large datasets with more rows than can fit in a 32-bit integer. This causes `nrow(df)` to be `NA`, and fails when we check if `NA > 2E7`. 

Solution is to cast the numbers as floats. Validated as working by the user who raised the issue.

## Motivation and Context

Fixes #51.

## How Has This Been Tested?

- Current unit tests pass

- Added testLargeDataWarning.R and ran locally. The negative test (that the warning doesn't appear for small data) is included in this PR,  but have excluded the test that prove it does fire with large data -  cannot easily add unit test for this, as large dataset generation kills travis CI. Unit tests were written and are commented out.

- User who raised issue confirmed the change fixed their issue

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ALMOST ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: dataCompareR/tests/testthat/testLargeDataWarning.R [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+
+test_that("Silent for small data", {
+  
+  expect_silent(warnLargeData(iris,iris))
+  expect_silent(warnLargeData(iris,pressure))
+  expect_silent(warnLargeData(pressure,pressure))
+})
+
+
+test_that("Warns for large data", {
```
Comment (sajohnston) [inline dataCompareR/tests/testthat/testLargeDataWarning.R]: One solution to the problem of unit testing is to make the function that does the check only take in the actual column and row counts, rather than the data frames. This of course means we still won't have a proper automated check for big data sets, but at least we could capture the part where it is sending a message for large values.

Outside of that, if we're going to have a unit test that Travis doesn't run within this file, then we should just comment out the entire `test_that` block, rather than putting in a meaningless placeholder like `expect_true(1==1)`.

**Comment by rnobleeddy** [comment]
I've had a go at fixing this, by

- refactoring the warning function to take row counts
- adding unit tests that are based on counts
