### PR TITLE
Fixing Issue #95

### LINKED ISSUE #95: Incorrectly flagging indices with duplicate values
See the simple example below:

Capture

### PR DESCRIPTION
**Pull request by sajohnston**
## Description
When using a multi-column index, dataCompareR merges the values of the columns to create an index. Previously, it was combining these by pasting them together without a separator. This meant that if two columns had different values that pasted together into the same value, an error would be raised when the comparison is actually made, saying that the indices are not unique. 

This pull request changes the paste logic to have an underscore as the separator to delineate between the column values, thus maintaining any uniqueness. 

## Motivation and Context
Fixes #95 

This creates a problem for anyone trying to use the package with this sort of data set.

## How Has This Been Tested?
I've added tests to two similar functions, `matchRows` and `matchMultiIndex` (which is called by `matchRows`). These tests show that when passing in two data frames that would have non-unique indices if pasted without a separator, the functions do not error and do produce the expected output. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: dataCompareR/tests/testthat/testMatchMultiIndex.R [hunk 1]
```diff
@@ -105,15 +105,11 @@ test_that("Merged indices remain unique in multi-index cases", {
...
-  ky2 <- c("b", "1b")
-  df2 <- data.frame(ky1, ky2, ky, stringsAsFactors = FALSE)
+  # Second data frame. Same as first
+  df2 <- df1
   
-  ky <- c(1, 2)
-  ky1 <- c("a1", "a")
-  ky2 <- c("b", "1b")
-  dfMtch <- data.frame(ky1, ky2, ky, stringsAsFactors = FALSE)
+  # Matching data fame will be the same as well
```
Comment (KrishanBhasin) [inline dataCompareR/tests/testthat/testMatchMultiIndex.R:111]:
```suggestion
  # Matching data frame will be the same as well
```

File: dataCompareR/tests/testthat/testMatchRows.R [hunk 2]
```diff
@@ -177,16 +177,12 @@ test_that("Merged indices remain unique in multi-index cases", {
...
-  
-  ky <- c(1, 2)
-  ky1 <- c("a1", "a")
-  ky2 <- c("b", "1b")
-  dfMtch <- data.frame(ky1, ky2, ky, stringsAsFactors = FALSE)
+
+  # Second data frame. Same as first
+  df2 <- df1
+
+  # Matching data fame will be the same as well
```
Comment (KrishanBhasin) [inline dataCompareR/tests/testthat/testMatchRows.R:184]:
```suggestion
  # Matching data frame will be the same as well
```
